import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

const terms = [
  {
    heading: 'Use of the platform',
    details: 'AstraFlow is provided under subscription terms that allow your organization to operate outreach campaigns, analytics dashboards, and AI workflows in accordance with our acceptable use policies.',
  },
  {
    heading: 'Intellectual property',
    details: 'All platform components, creative assets, and product UI remain the property of AstraFlow, while data generated by your campaigns belongs to your organization.',
  },
  {
    heading: 'Service commitments',
    details: 'We offer enterprise-grade support and availability commitments, extended by custom service level agreements for qualifying customers.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-950">
      <Navbar />
      <main className="container space-y-14 py-20">
        <section className="space-y-4 text-center">
          <p className="text-sm uppercase tracking-[0.3em] text-slate-900">Terms of service</p>
          <h1 className="text-5xl font-semibold tracking-tight text-slate-950">Modern terms for modern enterprise SaaS.</h1>
          <p className="mx-auto max-w-3xl text-base leading-8 text-slate-600">
            These terms govern your access to AstraFlow, describe how we work together, and clarify the rights and responsibilities of both parties.
          </p>
        </section>

        <section className="space-y-8">
          {terms.map((term) => (
            <article key={term.heading} className="rounded-[32px] border border-slate-200 bg-slate-100 p-10 shadow-soft">
              <h2 className="text-2xl font-semibold text-slate-950">{term.heading}</h2>
              <p className="mt-4 text-base leading-8 text-slate-700">{term.details}</p>
            </article>
          ))}
        </section>

        <section className="rounded-[32px] border border-slate-200 bg-white p-10 shadow-soft">
          <h2 className="text-3xl font-semibold text-slate-950">Billing, cancellations, and renewals</h2>
          <p className="mt-4 max-w-3xl text-base leading-8 text-slate-600">
            Subscriptions are billed monthly or annually depending on your selected plan. Cancellation takes effect at the end of your current billing period, and renewals continue automatically unless otherwise agreed.
          </p>
        </section>
      </main>
      <Footer />
    </div>
  );
}
